# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- master


pool:
  vmImage: vs2017-win2016

steps:

- task: UseRubyVersion@0
  inputs:
    versionSpec: '~= 2.4'
    addToPath: true

- pwsh: |
    $rubyFolder = (Get-Item -Path ((Get-Command -Name ruby).Source)).Directory.FullName
    Copy-Item -Path .\csvlint\libcurl.dll -Destination "$rubyFolder" -Verbose
  displayName: copy libcurl.dll to $rubyLocation
  
- pwsh: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- pwsh: |
    bundle exec rake
  displayName: 'bundle exec rake'

- pwsh: |
    bundle exec ocra --console "./bin/csvlint" --no-autoload --dll 'libcurl.dll' --gem-all --output './csvlint.exe'
  displayName: Build csvlint.exe

- pwsh: |
    bundle exec ocra --console "./bin/create_schema" --no-autoload --dll 'libcurl.dll' --gem-all --output './create_schema.exe'
  displayName: Build create_schema.exe

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/'
    Contents: '*.exe'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/csvlint'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/csvlint/'
    ArtifactName: 'csvlint'
    publishLocation: Container