# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- master


pool:
  vmImage: vs2017-win2016

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.6'
    addToPath: true

- script: |
    gem install ocra 
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: bundle exec rake
  displayName: 'bundle exec rake'
